name: crypto
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/gif/


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
